---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: tag_Name_webserver
  remote_user: ec2-user
  become: true
  become_method: sudo

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: tag_Name_dbserver
  remote_user: ec2-user
  become: true
  become_method: sudo

  roles:
    - db
